import Head from "next/head";
import styles from "../styles/profile.module.css";
import { useState, useEffect } from "react";
import { getUserData, updateUserData } from "../firebase";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const [data, setData] = useState(null);
  const [isLoading, setLoading] = useState(false);
  const [name, setName] = useState("");
  const [college, setCollege] = useState("");
  const [year, setYear] = useState("");
  const [major, setMajor] = useState("");
  const [interests, setInterests] = useState("");
  const [currentClasses, setCurrentClasses] = useState("");
  const [gender, setGender] = useState("");

  useEffect(() => {
    setLoading(true);
    getUserData("jkelly").then((data) => {
      setData(data);
      setName(data.name);
      setCollege(data.college);
      setYear(data.year);
      setMajor(data.major);
      setInterests(data.interests);
      setCurrentClasses(data.currentClassses);
      setGender(data.gender);
      setLoading(false);
    });
  }, []);

  if (isLoading) return <p></p>;
  if (!data) return <p></p>;

  const handleChangeName = (event) => {
    setName(event.target.value);
    console.log("value is:", event.target.value);
  };
  const handleChangeCollege = (event) => {
    setCollege(event.target.value);

    console.log("value is:", event.target.value);
  };
  const handleChangeYear = (event) => {
    setYear(event.target.value);

    console.log("value is:", event.target.value);
  };
  const handleChangeMajor = (event) => {
    setMajor(event.target.value);

    console.log("value is:", event.target.value);
  };
  const handleChangeInterests = (event) => {
    setInterests(event.target.value);

    console.log("value is:", event.target.value);
  };
  const handleChangeCurrentClasses = (event) => {
    setCurrentClasses(event.target.value);

    console.log("value is:", event.target.value);
  };
  const handleChangeGender = (event) => {
    setGender(event.target.value);

    console.log("value is:", event.target.value);
  };

  const submitChange = (event) => {
    updateUserData(
      "jkelly",
      event.target.name.value,
      event.target.year.value,
      event.target.major.value,
      event.target.gender.value,
      event.target.interests.value,
      event.target.college.value,
      event.target.currentClasses.value
    );
    router.push("/profile");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          height: "75%",
          width: "90%",
          position: "absolute",
          top: "0",
          bottom: "0",
          left: "0",
          right: "0",
          margin: "auto",
        }}
      >
        <div className={styles.center}>
          <div class="card" style={{ height: "35rem", width: "70rem" }}>
            <div class="card-body" style={{ height: "100%", width: "70rem" }}>
              <span>
                <h1 style={{ textAlign: "center" }}>{data.name}</h1>
              </span>
              <br></br>
              <br></br>
              <div class="container">
                <div class="row align-items-center justify-content-center">
                  <div class="col-sm-5 justify-content-center">
                    <img
                      src="/20.jpg"
                      style={{
                        display: "block",
                        margin: "auto",
                        width: "20rem",
                      }}
                      className={styles.profile}
                      alt="..."
                    ></img>
                  </div>
                  <div class="col-sm-7">
                    <form onSubmit={submitChange}>
                      <div
                        class="form-group row"
                        style={{ marginBottom: "5px" }}
                      >
                        <label for="name" class="col-sm-3 col-form-label">
                          Username
                        </label>
                        <div class="col-sm-9">
                          <input
                            type="text"
                            id="name"
                            name="name"
                            onChange={handleChangeName}
                            value={name}
                            class="form-control"
                          />
                        </div>
                      </div>

                      <div
                        class="form-group row"
                        style={{ marginBottom: "5px" }}
                      >
                        <label for="college" class="col-sm-3 col-form-label">
                          College
                        </label>
                        <div class="col-sm-9">
                          <input
                            type="text"
                            id="college"
                            name="college"
                            onChange={handleChangeCollege}
                            value={college}
                            class="form-control"
                          />
                        </div>
                      </div>

                      <div
                        class="form-group row"
                        style={{ marginBottom: "5px" }}
                      >
                        <label for="year" class="col-sm-3 col-form-label">
                          Year
                        </label>
                        <div class="col-sm-9">
                          <input
                            type="text"
                            id="year"
                            name="year"
                            onChange={handleChangeYear}
                            value={year}
                            class="form-control"
                          />
                        </div>
                      </div>

                      <div
                        class="form-group row"
                        style={{ marginBottom: "5px" }}
                      >
                        <label for="major" class="col-sm-3 col-form-label">
                          Major
                        </label>
                        <div class="col-sm-9">
                          <input
                            type="text"
                            id="major"
                            name="major"
                            onChange={handleChangeMajor}
                            value={major}
                            class="form-control"
                          />
                        </div>
                      </div>

                      <div
                        class="form-group row"
                        style={{ marginBottom: "5px" }}
                      >
                        <label for="interests" class="col-sm-3 col-form-label">
                          Interests
                        </label>
                        <div class="col-sm-9">
                          <input
                            type="text"
                            id="interests"
                            name="interests"
                            onChange={handleChangeInterests}
                            value={interests}
                            class="form-control"
                          />
                        </div>
                      </div>

                      <div
                        class="form-group row"
                        style={{ marginBottom: "5px" }}
                      >
                        <label
                          for="currentClasses"
                          class="col-sm-3 col-form-label"
                        >
                          Current Classes
                        </label>
                        <div class="col-sm-9">
                          <input
                            type="text"
                            id="currentClasses"
                            name="currentClasses"
                            onChange={handleChangeCurrentClasses}
                            value={currentClasses}
                            class="form-control"
                          />
                        </div>
                      </div>

                      <div
                        class="form-group row"
                        style={{ marginBottom: "5px" }}
                      >
                        <label for="gender" class="col-sm-3 col-form-label">
                          Gender
                        </label>
                        <div class="col-sm-9">
                          <input
                            type="text"
                            id="gender"
                            name="gender"
                            onChange={handleChangeGender}
                            value={gender}
                            class="form-control"
                          />
                        </div>
                      </div>
                      <button type="submit">Submit</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
