import Head from "next/head";
import styles from "../styles/profile.module.css";
import { useState, useEffect } from "react";
import { getUserData, updateUserData } from "../firebase";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const [data, setData] = useState(null);
  const [isLoading, setLoading] = useState(false);
  const [name, setName] = useState("");
  const [college, setCollege] = useState("");
  const [year, setYear] = useState("");
  const [major, setMajor] = useState("");
  const [interests, setInterests] = useState("");
  const [currentClasses, setCurrentClasses] = useState("");
  const [gender, setGender] = useState("");
  const [phoneNumber, setPhoneNumber] = useState("");
  const [email, setEmail] = useState("");
  const [bio, setBio] = useState("");

  useEffect(() => {
    setLoading(true);
    getUserData("jkelly").then((data) => {
      setData(data);
      setName(data.name);
      setCollege(data.college);
      setYear(data.year);
      setMajor(data.major);
      setInterests(data.interests);
      setCurrentClasses(data.currentClassses);
      setGender(data.gender);
      setPhoneNumber(data.phoneNumber);
      setEmail(data.email);
      setBio(data.bio);
      setLoading(false);
    });
  }, []);

  if (isLoading) return <p></p>;
  if (!data) return <p></p>;

  const handleChangeName = (event) => {
    setName(event.target.value);
    console.log("value is:", event.target.value);
  };
  const handleChangeCollege = (event) => {
    setCollege(event.target.value);

    console.log("value is:", event.target.value);
  };
  const handleChangeYear = (event) => {
    setYear(event.target.value);

    console.log("value is:", event.target.value);
  };
  const handleChangeMajor = (event) => {
    setMajor(event.target.value);

    console.log("value is:", event.target.value);
  };
  const handleChangeInterests = (event) => {
    setInterests(event.target.value);

    console.log("value is:", event.target.value);
  };
  const handleChangeCurrentClasses = (event) => {
    setCurrentClasses(event.target.value);

    console.log("value is:", event.target.value);
  };
  const handleChangeGender = (event) => {
    setGender(event.target.value);

    console.log("value is:", event.target.value);
  };

  const handleChangePhoneNumber = (event) => {
    setPhoneNumber(event.target.value);

    console.log("value is:", event.target.value);
  };

  const handleChangeEmail = (event) => {
    setEmail(event.target.value);

    console.log("value is:", event.target.value);
  };
  const handleChangeBio = (event) => {
    setBio(event.target.value);

    console.log("value is:", event.target.value);
  };

  const submitChange = (event) => {
    updateUserData(
      "jkelly",
      event.target.name.value,
      event.target.year.value,
      event.target.major.value,
      event.target.gender.value,
      event.target.interests.value,
      event.target.college.value,
      event.target.currentClasses.value
    );
    router.push("/profile");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          height: "75%",
          width: "90%",
          position: "absolute",
          top: "0",
          bottom: "0",
          left: "0",
          right: "0",
          margin: "auto",
        }}
      >
        <div className={styles.center}>
          <div
            class="card"
            style={{
              position: "absolute",
              top: "-10px",
              width: "60%",
              height: "105%",
            }}
          >
            <div class="card-body" style={{ height: "100%", width: "80%" }}>
              <div style={{ textAlign: "left", width: "120%" }}>
                <div class="row" style={{ height: "30px" }}>
                  <div class="col-3" style={{ height: "200px" }}>
                    <img
                      src="/20.jpg"
                      style={{
                        display: "block",
                        margin: "auto",
                        width: "90px",
                        height: "90px",
                        position: "absolute",
                        top: "20px",
                        left: "50px",
                      }}
                      className={styles.profile}
                      alt="..."
                    ></img>
                  </div>
                  <div class="col-9" style={{ height: "200px" }}>
                    <br></br>
                    <h2
                      ClassName={styles.profileName}
                      style={{ fontSize: "40px" }}
                    >
                      {data.name.toLowerCase()}
                    </h2>
                  </div>
                </div>
                <Link href="/edit">
                  <img
                    style={{
                      float: "right",
                      marginTop: "-30px",
                      marginRight: "-20px",
                      width: "30px",
                    }}
                    src="/favicon2.ico"
                  ></img>
                </Link>
              </div>
              <br></br>
              <br></br>
              <br></br>
              <br></br>
              <form onSubmit={submitChange}>
                <div
                  class="container"
                  style={{ marginLeft: "26px", fontSize: "20px" }}
                >
                  <div class="row" style={{ height: "30px" }}>
                    <div class="col-5" style={{ height: "200px" }}>
                      name:
                    </div>
                    <div class="col-7" style={{ height: "200px" }}>
                      <input
                        type="text"
                        id="name"
                        name="name"
                        onChange={handleChangeName}
                        value={name}
                        class="form-control"
                        style={{ height: "28px" }}
                      />
                    </div>
                  </div>
                  <div class="row" style={{ height: "30px" }}>
                    <div class="col-5" style={{ height: "200px" }}>
                      pronouns:
                    </div>
                    <div class="col-7" style={{ height: "200px" }}>
                      <input
                        type="text"
                        id="gender"
                        name="gender"
                        onChange={handleChangeGender}
                        value={gender}
                        class="form-control"
                        style={{ height: "28px" }}
                      />
                    </div>
                  </div>
                  <div class="row" style={{ height: "30px" }}>
                    <div class="col-5" style={{ height: "200px" }}>
                      school:
                    </div>
                    <div class="col-7" style={{ height: "200px" }}>
                      <input
                        type="text"
                        id="college"
                        name="college"
                        onChange={handleChangeCollege}
                        value={college}
                        class="form-control"
                        style={{ height: "28px" }}
                      />
                    </div>
                  </div>
                  <div class="row" style={{ height: "30px" }}>
                    <div class="col-5" style={{ height: "200px" }}>
                      year:
                    </div>
                    <div class="col-7" style={{ height: "200px" }}>
                      <input
                        type="text"
                        id="year"
                        name="year"
                        onChange={handleChangeYear}
                        value={year}
                        class="form-control"
                        style={{ height: "28px" }}
                      />
                    </div>
                  </div>
                  <div class="row" style={{ height: "30px" }}>
                    <div class="col-5" style={{ height: "200px" }}>
                      major:
                    </div>
                    <div class="col-7" style={{ height: "200px" }}>
                      <input
                        type="text"
                        id="major"
                        name="major"
                        onChange={handleChangeMajor}
                        value={major}
                        class="form-control"
                        style={{ height: "28px" }}
                      />
                    </div>
                  </div>
                  <div class="row" style={{ height: "30px" }}>
                    <div class="col-5" style={{ height: "200px" }}>
                      current subjects:
                    </div>
                    <div class="col-7" style={{ height: "200px" }}>
                      <input
                        type="text"
                        id="currentClasses"
                        name="currentClasses"
                        onChange={handleChangeCurrentClasses}
                        value={currentClasses}
                        class="form-control"
                        style={{ height: "28px" }}
                      />
                    </div>
                  </div>
                  <div class="row" style={{ height: "30px" }}>
                    <div class="col-5" style={{ height: "200px" }}>
                      interests:
                    </div>
                    <div class="col-7" style={{ height: "200px" }}>
                      <input
                        type="text"
                        id="interests"
                        name="interests"
                        onChange={handleChangeInterests}
                        value={interests}
                        class="form-control"
                        style={{ height: "28px" }}
                      />
                    </div>
                  </div>
                  <div class="row" style={{ height: "30px" }}>
                    <div class="col-5" style={{ height: "200px" }}>
                      phone number:
                    </div>
                    <div class="col-7" style={{ height: "200px" }}>
                      <input
                        type="text"
                        id="phoneNumber"
                        name="phoneNumber"
                        onChange={handleChangePhoneNumber}
                        value={phoneNumber}
                        class="form-control"
                        style={{ height: "28px" }}
                      />
                    </div>
                  </div>
                  <div class="row" style={{ height: "30px" }}>
                    <div class="col-5" style={{ height: "200px" }}>
                      email:
                    </div>
                    <div class="col-7" style={{ height: "200px" }}>
                      <input
                        type="text"
                        id="email"
                        name="email"
                        onChange={handleChangeEmail}
                        value={email}
                        class="form-control"
                        style={{ height: "28px" }}
                      />
                    </div>
                  </div>
                </div>
                <br></br>
                <div
                  class="container"
                  style={{ marginLeft: "26px", fontSize: "20px" }}
                >
                  <div class="row" style={{ height: "30px" }}>
                    <div class="col-5" style={{ height: "200px" }}>
                      bio:
                    </div>
                    <div class="col-7" style={{ height: "200px" }}></div>
                  </div>
                </div>
                <div
                  class="container"
                  style={{
                    height: "100px",
                    width: "110%",
                    marginLeft: "40px",
                  }}
                >
                  <textarea
                    id="bio"
                    name="bio"
                    onChange={handleChangeBio}
                    value={bio}
                    class="form-control"
                    style={{
                      height: "100%",
                      width: "105%",
                      marginLeft: "-12px",
                      border: "solid black 0.5px",
                    }}
                  />
                </div>
                <br></br>
                <div class="row">
                  <button
                    type="submit"
                    class="btn btn-warning"
                    style={{ marginLeft: "50%", width: "100px" }}
                  >
                    Submit
                  </button>
                </div>
              </form>
              <br></br>
              <br></br>
              <br></br>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
