import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { LoginBox } from '../components/LoginBox';
import { SignupBox } from '../components/SignupBox';

export default function Home() {
  const LOGIN_MODE = 0;
  const SIGNUP_MODE = 1;
  const [mode, changeMode] = useState(LOGIN_MODE)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center h-screen bg-gray-100">
        <div className="flex flex-col justify-center items-center border rounded p-8 shadow-md bg-white w-2/5">
          <div className='py-8 text-xl font-bold'>
            CramWithMe
          </div>
          {mode == LOGIN_MODE ? <LoginBox /> : <SignupBox />}
          <div onClick={mode == LOGIN_MODE ? () => changeMode(SIGNUP_MODE) : () => changeMode(LOGIN_MODE)} className="cursor-pointer text-blue-400">
            {mode == LOGIN_MODE ? <span>Create an account</span> : <span>Already have an account? Sign In </span>}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
