import Head from "next/head";
import styles from "../styles/Home.module.css";
import Profile from "../components/ProfileCard";
import { writeUserData } from "../firebase";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div
          style={{
            height: "75%",
            width: "90%",
            position: "absolute",
            top: "0",
            bottom: "0",
            left: "0",
            right: "0",
            margin: "auto",
          }}
        >
          <Profile username="jkelly"></Profile>
        </div>
      </main>
    </div>
  );
}

// import { useSelector } from "react-redux"
// export default function Profile() {
//     const uid = useSelector((state) => state.userCredReducer.uid)
//     const email = useSelector((state) => state.userCredReducer.email)
//     const photoURL = useSelector((state) => state.userCredReducer.photoURL)
//     // const states = useSelector((state) => state)
//     // console.log(states)
//     return (<div>
//         {uid} <br />
//         {email} <br />
//         {photoURL} <br />
//     </div>)
// }